os:
  - osx
  - linux

language: 
  - cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_SHARED=ON
  - BUILD_SHARED=OFF

script:
  - mkdir build
  - cd build
  - cmake -DNSW_BUILD_SHARED=$BUILD_SHARED -DNSW_BUILD_DOC=OFF -DNSW_BUILD_EXAMPLES=ON -DBUILD_TESTING=ON ..
  - cmake --build . -- -j2
  - ctest

matrix:
  exclude:
  - os: osx
    compiler: gcc
